package com.orbitastra.backend.models.institution.enums;

/**
 * Business document or identity number generated by NumberSequence.
 */
public enum NumberSequenceType {
    /** Pre-application CRM inquiry number. */
    ADMISSION_INQUIRY,

    /** Formal admission application number. */
    ADMISSION_APPLICATION,

    /** Formal admission offer number. */
    ADMISSION_OFFER,

    /** Permanent student admission number assigned after enrollment. */
    STUDENT_ADMISSION,

    /** Student roll number within its configured scope. */
    STUDENT_ROLL_NUMBER,

    /** Permanent employee/staff number. */
    EMPLOYEE_NUMBER,

    /** Staff leave request number. */
    STAFF_LEAVE_REQUEST,

    /** School fee invoice number. */
    FEE_INVOICE,

    /** School fee receipt number, allocated only once a payment succeeds. */
    FEE_RECEIPT,

    /** School fee payment number, allocated when the payment is first recorded. */
    FEE_PAYMENT,

    /** Fee refund number. */
    FEE_REFUND,

    /** Fee concession request number. */
    CONCESSION_REQUEST,

    /** Student wallet account number. */
    WALLET_ACCOUNT,

    /** Financial aid or scholarship application number. */
    AID_APPLICATION,

    /** Financial aid or scholarship award number. */
    AID_AWARD,

    /** UPI AutoPay mandate number. */
    UPI_MANDATE,

    /** SaaS subscription invoice number. */
    // The subscription itself, not a bill for one. Added 2026-09-03 with endpoint #13: a
    // subscription carries a human-quotable number ("SUB/2026/000001") that support and finance
    // use to name it, and there was a type for its invoices and its payments but not for it.
    SUBSCRIPTION,

    SUBSCRIPTION_INVOICE,

    /** SaaS subscription payment number. */
    SUBSCRIPTION_PAYMENT,

    /** Generated certificate number. */
    CERTIFICATE,

    /** Request from a parent or student for a document. */
    DOCUMENT_REQUEST,

    /** Identity card number, printed on the card. */
    ID_CARD,

    /** Visitor pass number. */
    VISITOR_PASS,

    /** Permission for a student to leave during school hours. */
    STUDENT_OUT_PASS,

    /** One visit to the school nurse. */
    CLINIC_VISIT,

    /** One conduct incident, which may involve several students. */
    CONDUCT_EVENT,

    /** One student's conduct case arising from an incident. */
    CONDUCT_CASE,

    /** One recognition or award given to a student. */
    STUDENT_RECOGNITION,

    /** Accession number written inside a book when it joins the library. */
    BOOK_ACCESSION,

    /** One student's hostel bed for a year. */
    HOSTEL_ALLOCATION,

    /** A boarder's request to go home and come back. */
    HOSTEL_LEAVE_REQUEST,

    /** Stock given out that is expected back. */
    STOCK_ISSUE,

    /** Code for a new inventory item, so a store need not invent hundreds by hand. */
    INVENTORY_ITEM,

    /** The number physically stuck on one tracked object. Never reused, even after disposal. */
    ASSET_TAG,

    /** One job of maintenance work. */
    MAINTENANCE_WORK_ORDER,

    /** One safety or condition inspection, quoted on the certificate it produces. */
    FACILITY_INSPECTION,

    /** One request to use a hall, lab or ground. */
    RESOURCE_BOOKING,

    /** Short code for a business the school buys from. */
    VENDOR,

    /** A department's request to buy something, raised before any money is committed. */
    PROCUREMENT_REQUEST,

    /** An order placed with a vendor. Quoted by the vendor on their bill. */
    PURCHASE_ORDER,

    /** One delivery, as received and checked at the store. */
    GOODS_RECEIPT,

    /** The school's own number for a bill a vendor has sent. */
    SUPPLIER_INVOICE,

    /** One payment made to a vendor. */
    VENDOR_PAYMENT,

    /** One member of staff's payslip for one month. */
    PAYSLIP,

    /** One student's plan for extra help with learning. */
    SUPPORT_PLAN,

    /**
     * One piece of feedback. Numbered even when anonymous, so somebody can be told their
     * feedback was acted on without anybody knowing whose it was.
     */
    FEEDBACK_SUBMISSION,

    /** One report sent straight to the head, at a time nobody asked for it. */
    FEEDBACK_REPORT,

    /** School-configured type not represented above. */
    CUSTOM
}
