package com.orbitastra.backend.models.institution.enums;

/**
 * Business document or identity number generated by NumberSequence.
 */
public enum NumberSequenceType {
    /** 01. Pre-application CRM inquiry number. */
    ADMISSION_INQUIRY,

    /** 02. Formal admission application number. */
    ADMISSION_APPLICATION,

    /** 03. Formal admission offer number. */
    ADMISSION_OFFER,

    /** 04. Permanent student admission number assigned after enrollment. */
    STUDENT_ADMISSION,

    /** 05. Student roll number within its configured scope. */
    STUDENT_ROLL_NUMBER,

    /** 06. Permanent employee/staff number. */
    EMPLOYEE_NUMBER,

    /** 07. Staff leave request number. */
    STAFF_LEAVE_REQUEST,

    /** 08. School fee invoice number. */
    FEE_INVOICE,

    /** 09. School fee receipt number, allocated only once a payment succeeds. */
    FEE_RECEIPT,

    /** 10. School fee payment number, allocated when the payment is first recorded. */
    FEE_PAYMENT,

    /** 11. Fee refund number. */
    FEE_REFUND,

    /** 12. Fee concession request number. */
    CONCESSION_REQUEST,

    /** 13. Student wallet account number. */
    WALLET_ACCOUNT,

    /** 14. Financial aid or scholarship application number. */
    AID_APPLICATION,

    /** 15. Financial aid or scholarship award number. */
    AID_AWARD,

    /** 16. UPI AutoPay mandate number. */
    UPI_MANDATE,

    /** 17. SaaS subscription number, for the subscription itself and not a bill for one. */
    // Added 2026-09-03 with endpoint #13: a subscription carries a human-quotable number
    // ("SUB/2026/000001") that support and finance use to name it, and there was a type for its
    // invoices and its payments but not for it.
    SUBSCRIPTION,

    /** 18. SaaS subscription invoice number. */
    SUBSCRIPTION_INVOICE,

    /** 19. SaaS subscription payment number. */
    SUBSCRIPTION_PAYMENT,

    /** 20. Generated certificate number. */
    CERTIFICATE,

    /** 21. Request from a parent or student for a document. */
    DOCUMENT_REQUEST,

    /** 22. Identity card number, printed on the card. */
    ID_CARD,

    /** 23. Visitor pass number. */
    VISITOR_PASS,

    /** 24. Permission for a student to leave during school hours. */
    STUDENT_OUT_PASS,

    /** 25. One visit to the school nurse. */
    CLINIC_VISIT,

    /** 26. One conduct incident, which may involve several students. */
    CONDUCT_EVENT,

    /** 27. One student's conduct case arising from an incident. */
    CONDUCT_CASE,

    /** 28. One recognition or award given to a student. */
    STUDENT_RECOGNITION,

    /** 29. Accession number written inside a book when it joins the library. */
    BOOK_ACCESSION,

    /** 30. One student's hostel bed for a year. */
    HOSTEL_ALLOCATION,

    /** 31. A boarder's request to go home and come back. */
    HOSTEL_LEAVE_REQUEST,

    /** 32. Stock given out that is expected back. */
    STOCK_ISSUE,

    /** 33. Code for a new inventory item, so a store need not invent hundreds by hand. */
    INVENTORY_ITEM,

    /** 34. The number physically stuck on one tracked object. Never reused, even after disposal. */
    ASSET_TAG,

    /** 35. One job of maintenance work. */
    MAINTENANCE_WORK_ORDER,

    /** 36. One safety or condition inspection, quoted on the certificate it produces. */
    FACILITY_INSPECTION,

    /** 37. One request to use a hall, lab or ground. */
    RESOURCE_BOOKING,

    /** 38. Short code for a business the school buys from. */
    VENDOR,

    /** 39. A department's request to buy something, raised before any money is committed. */
    PROCUREMENT_REQUEST,

    /** 40. An order placed with a vendor. Quoted by the vendor on their bill. */
    PURCHASE_ORDER,

    /** 41. One delivery, as received and checked at the store. */
    GOODS_RECEIPT,

    /** 42. The school's own number for a bill a vendor has sent. */
    SUPPLIER_INVOICE,

    /** 43. One payment made to a vendor. */
    VENDOR_PAYMENT,

    /** 44. One member of staff's payslip for one month. */
    PAYSLIP,

    /** 45. One student's plan for extra help with learning. */
    SUPPORT_PLAN,

    /**
     * 46. One piece of feedback. Numbered even when anonymous, so somebody can be told their
     * feedback was acted on without anybody knowing whose it was.
     */
    FEEDBACK_SUBMISSION,

    /** 47. One report sent straight to the head, at a time nobody asked for it. */
    FEEDBACK_REPORT,

    /** 48. School-configured type not represented above. */
    CUSTOM
}
