package com.orbitastra.backend.models.undone.a_working.celebrations;

import java.time.LocalDateTime;

import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import com.orbitastra.backend.models.base.SchoolBase;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

@Document(collection = "birthday_greetings")
@Data
@EqualsAndHashCode(callSuper = true)
@SuperBuilder
@NoArgsConstructor
@AllArgsConstructor
public class BirthdayGreeting extends SchoolBase {

    /**
     * Student/Staff member whose birthday is being celebrated.
     */
    @Indexed
    private String birthdayPersonDocsId;

    /**
     * User who sent the greeting.
     */
    @Indexed
    private String senderDocsId;

    /**
     * Birthday wish/message.
     */
    private String message;

    /**
     * Optional image attached to the greeting.
     */
    private String imageUrl;

    /**
     * Whether the sender's identity is hidden.
     */
    @Builder.Default
    private Boolean anonymous = false;

    /**
     * Whether this greeting was generated automatically by the system.
     */
    @Builder.Default
    private Boolean autoGenerated = false;

    /**
     * Time the greeting was sent/generated.
     */
    @Indexed
    private LocalDateTime sentAt;
}