package com.orbitastra.backend.dto.student.student.request;

import java.time.LocalDate;
import java.util.List;

import com.orbitastra.backend.models.common.enums.CountryCode;
import com.orbitastra.backend.models.common.enums.Gender;
import com.orbitastra.backend.models.common.enums.GuardianRelation;
import com.orbitastra.backend.models.common.enums.SchoolLocale;

import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Past;
import jakarta.validation.constraints.Size;

/**
 * What #1 needs to admit a child.
 *
 * <p><b>There is no {@code admissionNo} here.</b> It is generated from
 * {@code NumberSequenceType.STUDENT_ADMISSION}, the same call staff numbers are generated by.
 * Nobody picks their own admission number, and a caller-supplied one lets two children collide.
 *
 * <p><b>There is no academic year and no class either.</b> The child is created first and placed
 * second, which is the flow this project recorded long before this endpoint existed: a school
 * knows it has admitted a child before it knows which section they are in. A student with no
 * academic record is a normal state, not a half-finished one.
 *
 * <p><b>At least one guardian is required.</b> A child the school holds no way of contacting is
 * not a record worth having, and every school's own admission form asks for one.
 */
public record StudentCreateRequest(

        @NotBlank @Size(max = 160) String fullName,

        /** Must be in the past. A child born tomorrow is a typo, not an admission. */
        @NotNull @Past LocalDate dateOfBirth,

        @NotNull Gender gender,

        /**
         * The day the school admitted them. <b>Defaults to today when it is left out</b>, which is
         * the ordinary case — somebody filling the form in is doing it on the day.
         *
         * <p>A past date is allowed on purpose: a school typing in the roll it already had needs
         * to say when each child actually joined.
         */
        LocalDate admissionDate,

        /**
         * Who the school contacts. <b>At least one, and exactly one of them has to be the primary
         * contact</b> — "ring the family" has to resolve to one number.
         *
         * <p><b>These are matched, not blindly created.</b> See {@link GuardianRequest}.
         */
        @NotEmpty @Size(max = 10) List<@Valid GuardianRequest> guardians,

        /** The child's own, from the closed set. Absent is fine — most schools do not record it. */
        CountryCode nationalityCode,

        /** The language the family is written to in. */
        SchoolLocale preferredLanguage,

        /** The student's <b>own</b> phone, for an older child. Their guardian's goes below. */
        @Size(max = 40) String phoneNumber,

        @Size(max = 160) String emailAddress,

        /**
         * The admission application this child came from, set by {@code crm} #33.
         *
         * <p><b>A direct caller leaves it out</b>, and that is the normal case: a transfer, a
         * walk-in, or a school typing in the roll it already has. One application produces one
         * child — {@code school_admission_application_uniq} is unique and partial on this field
         * being there.
         */
        @Size(max = 60) String admissionApplicationDocsId) {

    /**
     * One contact on the admission form.
     *
     * <p><b>Guardians are matched, not blindly created</b>, and that is the single most important
     * thing about this endpoint. A phone number identifies one person within a school — the
     * database says so, {@code school_guardian_phone_uniq} is unique — and <b>two siblings share a
     * father</b>. Writing a new guardian row per child would fail on a duplicate key the first
     * time a second child in a family was admitted.
     *
     * <p>So for each entry: if the phone matches somebody already here, <b>that person is linked
     * and their stored name is left alone</b>; otherwise a new guardian is written. The response
     * says which happened, per guardian, because a silent match is how one child's father quietly
     * becomes another's.
     *
     * <p><b>A guardian with no phone and no email is always a new row.</b> Nothing identifies
     * them, so a family that gives no contact details will slowly collect duplicates. That is
     * known and accepted rather than solved.
     */
    public record GuardianRequest(

            @NotBlank @Size(max = 160) String fullName,

            @NotNull GuardianRelation relation,

            /**
             * <b>The match key.</b> Stored stripped of spaces and punctuation, so "+91 98765
             * 43210" and "9876543210" are the same person rather than two.
             */
            @Size(max = 40) String phoneNumber,

            /** The second match key, tried only when the phone found nobody. Stored lowercase. */
            @Size(max = 160) String emailAddress,

            /**
             * A second number for the same person — often "my husband's phone".
             *
             * <p><b>Not a match key and not unique</b>, because a family shares one landline and
             * matching on it would make a mother and a father one person.
             */
            @Size(max = 40) String alternatePhoneNumber,

            @Size(max = 400) String address,

            @Size(max = 120) String occupation,

            SchoolLocale preferredLanguage,

            /**
             * The person the school rings first. <b>Exactly one guardian in the list must be
             * this</b> — none means nobody to ring, two means the question has no answer.
             */
            Boolean primaryContact,

            Boolean emergencyContact,

            /** May collect the child. */
            Boolean pickupAuthorized,

            /** May be given a login to the guardian portal, when that portal exists. */
            Boolean portalAccess) {
    }
}
