package com.orbitastra.backend.models.new_new.institution.enums;

/**
 * Business document or identity number generated by NumberSequence.
 */
public enum NumberSequenceType {
    /** Pre-application CRM inquiry number. */
    ADMISSION_INQUIRY,

    /** Formal admission application number. */
    ADMISSION_APPLICATION,

    /** Formal admission offer number. */
    ADMISSION_OFFER,

    /** Permanent student admission number assigned after enrollment. */
    STUDENT_ADMISSION,

    /** Student roll number within its configured scope. */
    STUDENT_ROLL_NUMBER,

    /** Permanent employee/staff number. */
    EMPLOYEE_NUMBER,

    /** Staff leave request number. */
    STAFF_LEAVE_REQUEST,

    /** School fee invoice number. */
    FEE_INVOICE,

    /** School fee receipt number, allocated only once a payment succeeds. */
    FEE_RECEIPT,

    /** School fee payment number, allocated when the payment is first recorded. */
    FEE_PAYMENT,

    /** Fee refund number. */
    FEE_REFUND,

    /** Fee concession request number. */
    CONCESSION_REQUEST,

    /** Student wallet account number. */
    WALLET_ACCOUNT,

    /** Financial aid or scholarship application number. */
    AID_APPLICATION,

    /** Financial aid or scholarship award number. */
    AID_AWARD,

    /** Accounting journal entry number. */
    JOURNAL_ENTRY,

    /** UPI AutoPay mandate number. */
    UPI_MANDATE,

    /** SaaS subscription invoice number. */
    SUBSCRIPTION_INVOICE,

    /** SaaS subscription payment number. */
    SUBSCRIPTION_PAYMENT,

    /** Generated certificate number. */
    CERTIFICATE,

    /** Visitor pass number. */
    VISITOR_PASS,

    /** School-configured type not represented above. */
    CUSTOM
}
