package com.orbitastra.backend.models.new_new.institution.enums;

/**
 * Business document or identity number generated by NumberSequence.
 */
public enum NumberSequenceType {
    /** Pre-application CRM inquiry number. */
    ADMISSION_INQUIRY,

    /** Formal admission application number. */
    ADMISSION_APPLICATION,

    /** Formal admission offer number. */
    ADMISSION_OFFER,

    /** Permanent student admission number assigned after enrollment. */
    STUDENT_ADMISSION,

    /** Student roll number within its configured scope. */
    STUDENT_ROLL_NUMBER,

    /** Permanent employee/staff number. */
    EMPLOYEE_NUMBER,

    /** School fee invoice number. */
    FEE_INVOICE,

    /** School fee receipt number. */
    FEE_RECEIPT,

    /** SaaS subscription invoice number. */
    SUBSCRIPTION_INVOICE,

    /** SaaS subscription payment number. */
    SUBSCRIPTION_PAYMENT,

    /** Generated certificate number. */
    CERTIFICATE,

    /** Visitor pass number. */
    VISITOR_PASS,

    /** School-configured type not represented above. */
    CUSTOM
}
