package com.orbitastra.backend.models.new_new.academics.timetable.embedded;

import java.time.LocalTime;

import com.orbitastra.backend.models.new_new.academics.enums.TimetableSlotType;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/** One class/section period embedded in its owning DailyTimetable. */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TimetableEntry {

    // Generated by the service and unique inside the daily timetable.
    // Example: "entry_000124"
    @NotBlank
    private String entryId;

    // School-defined period identifier. Example: "P03"
    @NotBlank
    private String periodCode;

    // Links to SchoolClass.id. Example: "67aa15d9dc3f7d0011111111"
    @NotBlank
    private String classDocsId;

    // Stores the embedded ClassSection.name. Example: "Section A"
    @NotBlank
    private String sectionName;

    // Example: TimetableSlotType.LESSON
    @NotNull
    private TimetableSlotType slotType;

    // Required for LESSON; references SchoolClass.subjects[].subjectCode.
    // Example: "MATHEMATICS"
    private String subjectCode;

    // Links to the assigned Staff.id; null for breaks and assemblies.
    // Example: "67aa15d9dc3f7d0022222222"
    private String teacherDocsId;

    // Display label for BREAK, ASSEMBLY, or ACTIVITY. Example: "Lunch Break"
    private String slotLabel;

    // Example: 09:00:00
    @NotNull
    private LocalTime startTime;

    // Example: 09:45:00
    @NotNull
    private LocalTime endTime;
}
