package com.orbitastra.backend.dto.people.staff.request;

import java.time.LocalDate;

import com.orbitastra.backend.models.common.enums.CountryCode;
import com.orbitastra.backend.models.common.enums.Gender;
import com.orbitastra.backend.models.common.enums.SchoolLocale;

import jakarta.validation.Valid;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Past;
import jakarta.validation.constraints.Size;

/**
 * A new person on a school's books. Endpoint #1.
 *
 * <h2>employeeNo is not here, and that is the point</h2>
 *
 * <p>It is generated by {@code NumberSequenceService}, atomically, per school. A caller-supplied
 * number lets two schools' conventions collide inside one tenant and lets two people be handed the
 * same one — and nobody should pick their own staff number. Sending it is ignored rather than
 * refused, the ordinary shape for a field the request record does not declare.
 *
 * <h2>Five required fields, and the plan said one</h2>
 *
 * <p>The module plan says {@code fullName} is the only one: "a school entering two hundred people
 * at the start of term has a name and nothing else on day one". Two rounds of decisions overruled
 * it, and both are worth keeping straight:
 *
 * <p><b>{@code dateOfBirth} and {@code gender}, because the model requires them</b> — decided
 * 2026-09-15, the same way {@code approvedHeadcount} followed the model over the plan at #13.
 * Nothing validates a document on save, so the plan's version would have stored rows that violate
 * their own declared constraints, invisible until something read them expecting a date.
 *
 * <p><b>{@code phoneNumber} and {@code emailAddress}, because the school asked for them</b> —
 * decided 2026-09-15. The model leaves both optional and this endpoint does not: a staff record
 * with no way to contact the person is one the office has to chase later, and "we will fill it in
 * afterwards" is what leaves 765 rows without a phone number.
 *
 * <p><b>Two things follow from that, and neither is obvious.</b> Both fields are unique per
 * school, so a duplicate is now reachable on every create rather than only when somebody happened
 * to supply one. And {@code ?hasEmail=false} on #7 — "who are we missing contact details for" —
 * can no longer match anybody created through this endpoint; it still matches the rows that
 * existed before this rule, which is exactly who that query is for.
 *
 * <h2>What a person is not</h2>
 *
 * <p><b>No {@code active}, no status, no department, no designation, no joining date.</b> A person
 * is not employed by existing: that is {@code EmploymentRecord} and #16. Every field here is a
 * fact about a human being, and that separation is the whole design of this package.
 *
 * <h2>Normalisation</h2>
 *
 * <pre>
 * emailAddress   trimmed and lower-cased      "  Anita@X.COM " -> "anita@x.com"
 * phoneNumber    spacing characters stripped  "+91 98765-43210" -> "+919876543210"
 * country codes  trimmed and upper-cased      "in" -> "IN"
 * </pre>
 *
 * <h2>A phone number and an email address each identify one person</h2>
 *
 * <p>Both are refused as duplicates within a school — {@code 409 STAFF_PHONE_TAKEN} and
 * {@code 409 STAFF_EMAIL_TAKEN}. <b>The module plan said the opposite about email</b> ("two staff
 * genuinely may share a family address"); that was overruled on 2026-09-15.
 *
 * <p><b>Both are optional and both indexes are partial</b>, so any number of people may have no
 * phone and no email. Only a value that is actually there has to be unique — a plain unique index
 * would have let one school hold exactly one person without a phone.
 */
public record StaffCreateRequest(

        /** The one field the plan called mandatory, and it still is. */
        @NotBlank @Size(max = 120) String fullName,

        /** Required by the model. Must be in the past — a person born tomorrow is a typo. */
        @NotNull @Past LocalDate dateOfBirth,

        /** Required by the model. The shared {@code Gender}, not a people-specific one. */
        @NotNull Gender gender,

        /**
         * ISO 3166-1 alpha-2, as a closed set — {@code "IN"}, not {@code "12"}.
         *
         * <p><b>The enum is the validation.</b> It was a free {@code String} until 2026-09-15,
         * which accepted anything two characters long; {@link CountryCode} is the same set
         * {@code School.countryCode} already uses, so a school and its staff cannot disagree
         * about what a country is.
         */
        CountryCode nationalityCode,

        /**
         * IETF language tag, from the set this product actually has strings for.
         *
         * <p><b>Curated, not exhaustive</b> — {@link SchoolLocale} is India's scheduled languages
         * plus English variants, the same set {@code School.defaultLocale} uses. Accepting any tag
         * the JDK knows would promise translations that do not exist.
         */
        SchoolLocale preferredLanguage,

        /**
         * Required. Stored with spacing characters stripped; a leading "+" is kept.
         *
         * <p><b>Unique within the school</b>, compared after normalising — so
         * {@code "+91 98765-43210"} collides with {@code "+919876543210"}.
         *
         * <p><b>A string of only punctuation is refused</b>, not stored as nothing: {@code "---"}
         * passes {@code @NotBlank} and normalises to empty, which would be a blank number wearing
         * a valid-looking request.
         */
        @NotBlank @Size(max = 32) String phoneNumber,

        /**
         * Required. Stored trimmed and lower-cased.
         *
         * <p><b>Unique within the school</b>, compared after lower-casing — so
         * {@code "Anita@X.com"} collides with {@code "anita@x.com"}.
         */
        @NotBlank @Email @Size(max = 160) String emailAddress,

        /** Where they live now. Omit it, or send it partly filled. */
        @Valid StaffAddressRequest currentAddress,

        /** Their permanent or legal address, which is often the same one. */
        @Valid StaffAddressRequest permanentAddress,

        /** Who to call. Omit it, or send it partly filled. */
        @Valid EmergencyContactRequest emergencyContact,

        /** A {@code DocumentRecord} id for the profile photo. #5 replaces it later. */
        @Size(max = 60) String profileImageDocsId) {

    /**
     * Trims the email before anything judges it.
     *
     * <p><b>{@code @Email} runs on the constructed record, and a compact constructor runs first</b>
     * — so without this, {@code "  anita@x.com  "} is refused as malformed. It is not malformed;
     * it is a paste from a spreadsheet, which is exactly how a school enters two hundred people.
     * Trimming here means the constraint judges the value that would actually be stored.
     *
     * <p><b>Only the email, and only trimming.</b> Lower-casing and every other normalisation
     * stays in the service where the rest of it lives — this is here because validation forces it
     * to be, not because request records are where normalising belongs.
     */
    public StaffCreateRequest {
        emailAddress = emailAddress == null ? null : emailAddress.trim();
    }
}
