package com.orbitastra.backend.models.academics;

import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.CompoundIndex;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import com.orbitastra.backend.models.academics.enums.SlotType;
import com.orbitastra.backend.models.base.SchoolBase;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * The complete timetable of ONE school for ONE date: a single document holding
 * the periods of every class and section on that day. A school year is at most
 * ~365 documents per school (fewer, because holidays and weekly offs are
 * skipped at creation time — no document is stored for them). The day of week
 * is derived from "date" on the client side.
 */
@Document(collection = "daily_timetables")
@CompoundIndex(name = "school_date_idx", def = "{'schoolId': 1, 'date': 1}", unique = true)
@Data
@EqualsAndHashCode(callSuper = true)
@SuperBuilder
@NoArgsConstructor
@AllArgsConstructor
public class DailyTimetable extends SchoolBase {

    // References AcademicYear.name (unique per school), e.g. "2026-2027".
    // Derived by the server from "date" — never taken from the request.
    @Indexed
    private String academicYear;

    @Indexed
    private LocalDate date;

    private List<TimetableEntry> entries;

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class TimetableEntry {
        // MongoDB ObjectId, generated by the service — Mongo only auto-generates
        // ids for top-level documents, not embedded ones. Lets a single entry
        // be edited/removed inside the day document.
        @Id
        private String id;

        private String classDocsId;

        private String section;

        // LESSON needs subject + teacherDocsId; BREAK has no teacher and the
        // subject is just a label like "Lunch". Breaks still occupy the
        // section's time, so nothing else can be scheduled over them.
        private SlotType type;

        private String subject;

        // Staff document id of the teacher (null for breaks)
        private String teacherDocsId;

        private LocalTime startTime;

        private LocalTime endTime;
    }
}
