package com.orbitastra.backend.models.institution;

import java.util.ArrayList;
import java.util.List;

import org.springframework.data.mongodb.core.index.CompoundIndex;
import org.springframework.data.mongodb.core.index.CompoundIndexes;
import org.springframework.data.mongodb.core.mapping.Document;

import com.orbitastra.backend.models.base.SchoolBase;
import com.orbitastra.backend.models.institution.embedded.SequenceCounter;

import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

/**
 * All of one school's human-readable business number counters, in one document.
 *
 * <p><b>Restructured on 2026-09-05.</b> Until then each counter was its own document, so a
 * provisioned school held 48 of them. Now there is exactly one document per school holding a
 * {@code counters} array, which is what the unique index on {@code schoolId} enforces.
 *
 * <p>The counters themselves did not change — see
 * {@link com.orbitastra.backend.models.institution.embedded.SequenceCounter}. What changed is
 * what the database can guarantee, and therefore what the service now has to.
 *
 * <h2>Three rules the service must follow</h2>
 *
 * <p><b>1. Allocate with the positional operator, never by reading and writing back.</b> The
 * old shape allowed a plain {@code $inc} on the document. The new one needs the array element
 * matched in the query and incremented through {@code $}:
 *
 * <pre>
 * findAndModify(
 *     query:  { schoolId: X, "counters.sequenceType": T, "counters.scopeKey": S },
 *     update: { $inc: { "counters.$.nextValue": 1 } },
 *     options: returnNew(false))
 * </pre>
 *
 * <p>That is still one atomic operation, and it still returns the pre-increment document so the
 * old value is the allocated number. Reading the array into Java, adding one and saving is how
 * two students get the same admission number.
 *
 * <p><b>2. Add a counter with a guarded {@code $push}, because no index can stop a duplicate.</b>
 * A unique index cannot protect {@code sequenceType + scopeKey} inside an array: Mongo
 * de-duplicates identical keys generated by one document, so two identical entries in the same
 * array are accepted. Two concurrent first-uses of the same type would each push one, and the
 * counter would then exist twice with the {@code $} operator only ever finding the first. The
 * condition has to be in the query:
 *
 * <pre>
 * updateOne(
 *     query:  { schoolId: X,
 *               counters: { $not: { $elemMatch: { sequenceType: T, scopeKey: S } } } },
 *     update: { $push: { counters: { ... } } })
 * </pre>
 *
 * <p>A matched count of zero then means "somebody else added it first", which is success, not
 * failure. <b>This replaces the protection the old
 * {@code school_sequence_type_scope_uniq} index gave for free.</b>
 *
 * <p><b>3. Never call {@code save()} on this document.</b> It inherits {@code @Version} from
 * AuditedDocument, so a full-document save takes part in optimistic locking — and with every
 * counter in the school now living here, two allocations at once would collide and one would
 * fail with {@code OptimisticLockingFailureException}. Targeted updates through MongoTemplate do
 * not touch the version and do not collide. Use them.
 *
 * <h2>What this shape costs, on the record</h2>
 *
 * <p><b>Every number in the school serialises on one document.</b> Before, a fee receipt and an
 * admission number incremented different documents and never contended. Now a bulk fee
 * collection, a bulk admission import and payroll all queue behind the same document-level
 * write lock.
 *
 * <p><b>The array grows and never shrinks.</b> An entry is per type <i>per scope</i>, and a new
 * scope means a new entry rather than a reset — that is the whole point of keeping last year's
 * count. Nothing resets yet, so today it is at most 48 entries. Once any type is put on
 * {@code MONTHLY} it gains twelve a year, forever, and 16MB is the ceiling for the document.
 * At roughly 200 bytes an entry that is a long way off, but it is a direction of travel, not a
 * resting place. <b>If reset policies are ever switched on, split the container by scope before
 * doing it</b> — one document per school per scope, keyed {@code schoolId + scopeKey}.
 *
 * <p>All of that was accepted deliberately, to keep one document per school instead of 48.
 */
@Document(collection = "number_sequences")
@CompoundIndexes({
        // One document per school, and this is what makes that true rather than a convention.
        //
        // schoolId is already @Indexed on SchoolBase, but only non-uniquely, and an inherited
        // field cannot be re-annotated here — so the uniqueness has to be declared as an index
        // on the class. Without it two documents could exist for one school, each holding a
        // different half of the counters, and every lookup would silently find whichever came
        // first.
        @CompoundIndex(name = "school_sequences_uniq", def = "{'schoolId': 1}", unique = true),

        // Makes the allocation query in rule 1 an index lookup rather than a scan of the array.
        // Multikey, because counters is an array. NOT unique: a unique multikey index would not
        // stop a duplicate entry inside one document anyway — see rule 2.
        @CompoundIndex(
                name = "school_counter_lookup_idx",
                def = "{'schoolId': 1, 'counters.sequenceType': 1, 'counters.scopeKey': 1}")
})
@Data
@EqualsAndHashCode(callSuper = true)
@SuperBuilder
@NoArgsConstructor
@AllArgsConstructor
public class NumberSequence extends SchoolBase {

    // Every counter this school has. Empty until the first number is issued, or filled by
    // complete-provisioning if it still seeds.
    //
    // schoolId, and everything else identifying the document, comes from SchoolBase. There is
    // no field of this class's own besides the array: the document IS the school's set of
    // counters.
    //
    // Identity inside the array is sequenceType + scopeKey. NOTHING IN THE DATABASE ENFORCES
    // THAT — see rule 2 in the class javadoc. A guarded $push is the only thing standing between
    // this array and two entries for one counter.
    @Valid
    @NotNull
    @Builder.Default
    private List<SequenceCounter> counters = new ArrayList<>();
}
