package com.orbitastra.backend.models.academics.timetable.embedded;

import java.time.LocalTime;

import org.springframework.data.mongodb.core.mapping.Field;
import org.springframework.data.mongodb.core.mapping.FieldType;

import com.orbitastra.backend.models.academics.enums.TimetableSlotType;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/** One class/section period embedded in its owning DailyTimetable. */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TimetableEntry {

    // Embedded MongoDB ObjectId generated by the service before insertion.
    // MongoDB does not auto-generate ids for embedded documents.
    // Example: "67aa15d9dc3f7d0011111111"
    @NotBlank
    @Field(name = "_id", targetType = FieldType.OBJECT_ID)
    private String id;

    // School-defined period identifier. Example: "P03"
    @NotBlank
    private String periodCode;

    // Links to SchoolClass.id. Example: "67aa15d9dc3f7d0011111111"
    @NotBlank
    private String classDocsId;

    // References an embedded SchoolClass.sections[].sectionNo. Example: "A"
    @NotBlank
    private String sectionNo;

    // Example: TimetableSlotType.LESSON
    @NotNull
    private TimetableSlotType slotType;

    // Required for LESSON; references SchoolClass.subjects[].subjectCode.
    // Example: "MATHEMATICS"
    private String subjectCode;

    // Links to the assigned Staff.id; null for breaks and assemblies.
    // Example: "67aa15d9dc3f7d0022222222"
    private String teacherDocsId;

    // Display label for BREAK, ASSEMBLY, or ACTIVITY. Example: "Lunch Break"
    private String slotLabel;

    // Example: 09:00:00
    @NotNull
    private LocalTime startTime;

    // Example: 09:45:00
    @NotNull
    private LocalTime endTime;

    // Links to FacilityResource.id for the room this happens in. Null where the school
    // does not allocate rooms, which is normal: in most Indian schools a section has one
    // classroom all day and the timetable moves teachers, not children.
    //
    // It matters for the periods that break that pattern — a physics practical in the lab,
    // games in the hall, computing in the computer room. Those are exactly the periods
    // where two sections can be sent to the same place at the same time, and where nobody
    // notices until thirty children are standing in a corridor.
    // Example: "67c31122dc3f7d0011223344"
    private String facilityResourceDocsId;
}
